---
- hosts: localhost
  #connection: local
  #gather_facts: no
  vars:
    remote_host: 1.1.1.1
  tasks:
   - name: Ping {{ remote_host }}
     command: 'ping -c 1 {{ remote_host }}'
     changed_when: false
